name: 04 workflow_run

on: 
  workflows: ["04 workflow_dispatch"]
  types:
    - completed

jobs:
  echo-hi-all:
    runs-ons: ubuntu-latest
    steps:
      - name: Echo hi all
        run: |
          echo "Hi all"