name: 04 workflow_dispatch

on:
  workflow_dispatch:
    inputs: 
      username: 
        description: 'Username'
        default: 'Carlos'
        required: true
        type: string
      
      age: 
        description: 'Age'
        required: true
        type: number

jobs:
  echo-username-age:
    runs-on: ubuntu-latest
    steps:
      - name: Echo username and age
        run: |
          echo "Username: ${{ inputs.username }}"
          echo "Age: ${{ inputs.age }}"
